apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: falco
spec:
  releaseName: falco
  chart:
    spec:
      chart: falco
      sourceRef:
        kind: HelmRepository
        name: falcosecurity
        namespace: flux-system
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/falcosecurity/charts/blob/master/falco/values.yaml
  values:
    falco:
      priority: warning