apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/argo
  - ../../../base/newrelic
  - ../../../base/actions-runner-controller
  #- get-dependabot-alerts.yaml
  - runners.yaml
patchesStrategicMerge:
  - argo-values.yaml
  - argocd-cm-values.yaml
  - ecr-sync.yaml
  - newrelic-values.yaml
  - actions-runner-controller-values.yaml
  