apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
   name: org-runner-qa
   namespace: actions-runner-system
spec:
  template:
    spec:
      organization: Omaze
      labels:
        - qa-eks
      env: []
---
apiVersion: actions.summerwind.dev/v1alpha1
kind: HorizontalRunnerAutoscaler
metadata:
  name: org-runner-hra-qa
  namespace: actions-runner-system
spec:
  scaleTargetRef:
    name: org-runner-qa
    # Uncomment the below in case the target is not RunnerDeployment but RunnerSet
    #kind: RunnerSet
  minReplicas: 1
  maxReplicas: 5
  scaleUpTriggers:
  - githubEvent:
      workflowJob: {}
    duration: "30m"
