apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: cicd
  namespace: flux-system
spec:
  interval: 10m0s
  dependsOn:
    - name: sources
    - name: controllers
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./cicd/americas/qa/us
  prune: true
  validation: client