apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: actions-runner-controller-github
spec:
  backendType: systemManager
  data:
    - path: /vendor/github/
      recursive: false