apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  namespace: argo
  name: argocd-github
spec:
  backendType: systemManager
  data:
    - path: /vendor/github/
      recursive: false
    - path: /infra/argocd/
      recursive: false
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  namespace: argo
  name: argocd-dex
spec:
  backendType: systemManager
  data:
    - path: /infra/argocd/
      recursive: false
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: http-credentials
  namespace: flux-system
spec:
  backendType: systemManager
  data:
    - key: /vendor/github/pat
      name: password
    - key: /vendor/github/user
      name: username
---
apiVersion: v1
kind: Secret
metadata:
  name: flux2
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/devopsidiot/gitops2022.git

---
apiVersion: v1
kind: Secret
metadata:
  name: helm-devopsidiot-deployment
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com:devopsidiot/terraform-modules.git//helm-deployment
---
apiVersion: v1
kind: Secret
metadata:
  name: helm-devopsidiot-cronjob
  namespace: argo
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com:devopsidiot/terraform-modules.git//helm-cronjob
---
apiVersion: "kubernetes-client.io/v1"
kind: ExternalSecret
metadata:
  name: private-repo-creds
  namespace: argo
spec:
  backendType: systemManager
  data:
    - key: /vendor/github/pat
      name: password
    - key: /vendor/github/user
      name: username
  template:
    metadata:
      labels:
        argocd.argoproj.io/secret-type: repo-creds
    stringData: 
      type: git
      url: https://github.com/devopsidiot