apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: secrets
spec:
  releaseName: secrets
  chart:
    spec:
      chart: kubernetes-external-secrets
      sourceRef:
        kind: HelmRepository
        name: secrets
        namespace: flux-system
      version: 7.2.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  # Default values
  # https://github.com/external-secrets/kubernetes-external-secrets/blob/master/charts/kubernetes-external-secrets/values.yaml
  values:
    env:
      AWS_REGION: us-east-1