apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../../base/alb
  - ../../../base/externaldns
  - ../../../base/secrets
  - ../../../base/metrics-server
  - ../../../base/cert-manager
  - ../../../base/aws-node-termination-handler
  - ../../../base/sops
  - ../../../base/priority-class
patchesStrategicMerge:
  - alb-values.yaml
  - secrets-values.yaml
  - sops-annotation.yaml
