apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata: 
  name: aws-node-termination-handler
spec:
  releaseName: aws-node-termination-handler
  chart:
    spec:
      chart: aws-node-termination-handler
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
      version: 0.17.0
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
  values:
    enableRebalanceMonitoring: true
    enableRebalanceDraining: true