apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: aws-load-balancer-controller
spec:
  releaseName: aws-load-balancer-controller
  chart:
    spec:
      chart: aws-load-balancer-controller
      sourceRef:
        kind: HelmRepository
        name: eks
        namespace: flux-system
      version: 1.4.1
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  # Default values
  # https://github.com/aws/eks-charts/blob/master/stable/aws-load-balancer-controller/values.yaml
  values:
    clusterName: js-qa-eks-0407-gOv4